### ISSUE TITLE
iOS 화면 디자인 수정

### ISSUE THREAD

**Issue by norang00** [DeveloperAcademy-POSTECH/2024-MC2-A01-LittleHiker#102]
### Descrpiton
iOS 화면 미완성 부분들 작업합니다.

### Todo
- [ ] 타이틀 미지정시 디폴트로 날짜 들어가도록 지정해두기
- [x] 산행 기록 없을 때도 타이틀이 윗부분에 고정되도록 하기
- [x] Appearance .dark 로 고정하기
- [x] Figma 최종 디자인 반영
