### ISSUE TITLE
데이터를 ios 화면에 맞게 재구성하기

### ISSUE THREAD

**Issue by rokdam** [DeveloperAcademy-POSTECH/2024-MC2-A01-LittleHiker#95]
### Descrpiton
ios에 저장된 데이터를 디자인에 맞게 화면에 구성한다.

### Todo

- [x] 저장된 데이터 불러오기
- [ ] 상세화면의 스위프트(충격량) 차트 그리기
- [x] 리스트화면에서 디테일 화면 넘어가는 뷰모델 조절
